/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue-next/components/BButton')['BButtonToolbar']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckboxGroup']
    BFormSpinbutton: typeof import('bootstrap-vue-next/components/BFormSpinbutton')['BFormSpinbutton']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavText: typeof import('bootstrap-vue-next/components/BNav')['BNavText']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    IBiCircleFill: typeof import('~icons/bi/circle-fill')['default']
    IBiDot: typeof import('~icons/bi/dot')['default']
    IBiPauseFill: typeof import('~icons/bi/pause-fill')['default']
    IBiPlayFill: typeof import('~icons/bi/play-fill')['default']
    IBiSkipBackwardFill: typeof import('~icons/bi/skip-backward-fill')['default']
    IBiSkipEndFill: typeof import('~icons/bi/skip-end-fill')['default']
    IBiSkipForwardFill: typeof import('~icons/bi/skip-forward-fill')['default']
    IBiSkipStartFill: typeof import('~icons/bi/skip-start-fill')['default']
    IBiStopFill: typeof import('~icons/bi/stop-fill')['default']
    IBiVolumeMute: typeof import('~icons/bi/volume-mute')['default']
    IBiVolumeUp: typeof import('~icons/bi/volume-up')['default']
    ListIterator: typeof import('./src/components/base/ListIterator.vue')['default']
    ListNavigator: typeof import('./src/components/base/ListNavigator.vue')['default']
    MainBarLeft: typeof import('./src/components/MainBarLeft.vue')['default']
    MainBarRight: typeof import('./src/components/MainBarRight.vue')['default']
    MediaPlayer: typeof import('./src/components/MediaPlayer.vue')['default']
    MediaSelector: typeof import('./src/components/MediaSelector.vue')['default']
    NavBarTitle: typeof import('./src/components/base/NavBarTitle.vue')['default']
    OptionSettings: typeof import('./src/components/OptionSettings.vue')['default']
    PlayControl: typeof import('./src/components/base/PlayControl.vue')['default']
    RecorderController: typeof import('./src/components/RecorderController.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowNotes: typeof import('./src/components/ShowNotes.vue')['default']
    SongpartSelector: typeof import('./src/components/SongpartSelector.vue')['default']
    SongSelector: typeof import('./src/components/SongSelector.vue')['default']
    TempoSelector: typeof import('./src/components/TempoSelector.vue')['default']
    TimeSignatureSelector: typeof import('./src/components/TimeSignatureSelector.vue')['default']
    TransportController: typeof import('./src/components/TransportController.vue')['default']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
